### PR TITLE
validate-release: various rewrites

### PR DESCRIPTION
**Pull request by illwieckz**
- proper shebang
- per-arch linux lib versions
- declare logic more than results (more constraints means more verifications)
- deduplicate Windows checker
- unify some wording
- etc.

### CODE REVIEW

**Comment by illwieckz** [comment]
I have tested this against `unvanquished_0.54.0.zip`, and `linux-amd64.zip` and `symbols_0.54.0.zip` from it.

**Comment by illwieckz** [comment]
I still kept some bitness code (like `if bitness == 32`) in Windows checker that can be fully replaced by archness code (like `if arch == i686`), but I don't know if the given check is for all 32-bit Windows platforms if they exist (arm?) or specific to the x86 32-bit platform. Same for the 64-bit code: would it be the same for arm64 or is it specific to amd64?.

If those checks are truly bitness-specific and not arch-specific, extending the code to set bitness would be doable like that:

```diff
- bitness = [32, 64][arch == 'amd64']
+ bitness = [32, 64][arch in ['amd64', 'arm64']]
```

But we may also just do the `if arch === AX` where we do `if bitness == BX`.

**Comment by slipher** [comment]
Thanks. I merged most of this as 35977d35ffb4ab97880cb58ce595670789681845 with some very minor edits. The major exception is that I'm keeping the hard-coded list of expected symbol files :)

**Comment by illwieckz** [comment]
everything is merged but things that is now submitted as:

- https://github.com/Unvanquished/validate-release/pull/7

**Pull request closed without merging**
